'use client';
import React, { useEffect, useMemo, useState } from 'react';
import { apiUrl } from '@/lib/api-base';
import Link from 'next/link';
import { BusFront, ChevronRight, Clock3, CreditCard, MapPinned, MessageSquareText, PhoneCall, ShieldCheck, ShieldAlert, Star, CalendarRange, Route, Bell, User, Home, Activity, CheckCircle2 } from 'lucide-react';
import { listRideSnapshots } from '../../lib/ride/registry';
import { evaluateBookingCompliance, summarizeBookingCompliance } from '../../lib/safety-ops/booking-compliance';
import type { BookingRideCadence, BookingWeekday, OperationalConfidence, SmsUssdFallbackPayload, TransportLedgerTransaction, VehicleBookingPreference } from '../../types/polesafe';

const weekdays: BookingWeekday[] = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];

type RideStatus = 'waiting' | 'picked_up' | 'en_route' | 'dropped_off';
type ChildRide = { childName: string; school: string; route: string; status: RideStatus; pickupTime: string; maskedVehicleLocation: string; vehicleLabel: string; pickupProof: string; confidence: OperationalConfidence; };
type ScheduleItem = { term: string; route: string; days: string; pickup: string; dropoff: string; feeUgx: number; status: 'paid' | 'due' | 'partial'; };
const bookingDefaults: VehicleBookingPreference = { vehicleClass: 'car', cadence: 'weekly', paymentProvider: 'card', weeklyPattern: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'] };
const bookingComplianceSeed = evaluateBookingCompliance({ driver: { driverId: 'driver_001', nationalIdNumber: 'NIN-UG-002', status: 'verified', localTrustVerification: { status: 'verified', checkedAt: '2026-08-13T06:00:00Z', attentionRequired: false, trustDocuments: [{ type: 'nin', reference: 'NIN-UG-002', status: 'verified', aiGenerated: false, attentionRequired: false }, { type: 'driving_permit', reference: 'DPL-UG-022', status: 'verified', aiGenerated: false, attentionRequired: false }, { type: 'proof_of_ownership', reference: 'OWN-UG-455', status: 'verified', aiGenerated: false, attentionRequired: false }, { type: 'lc1_letter', url: '/docs/lc1.pdf', status: 'verified', aiGenerated: false, attentionRequired: false }] } } as any, vehicle: { driverId: 'vehicle_001', nationalIdNumber: 'NIN-UG-002', status: 'pending', localTrustVerification: { status: 'pending', checkedAt: '2026-08-13T06:00:00Z', attentionRequired: true, attentionReason: 'Vehicle ownership proof needs manual review', aiGeneratedRisk: true, aiGeneratedRiskScore: 0.81, trustDocuments: [{ type: 'nin', reference: 'NIN-UG-002', status: 'verified', aiGenerated: false, attentionRequired: false }, { type: 'proof_of_ownership', reference: 'OWN-UG-455', status: 'pending', aiGenerated: true, aiConfidence: 0.81, attentionRequired: true }, { type: 'stage_chairman_letter', url: '/docs/stage.pdf', status: 'pending', aiGenerated: false, attentionRequired: true }], alertRecipients: ['dispatcher', 'owner', 'compliance'] } } as any });
const bookingComplianceSummary = summarizeBookingCompliance(bookingComplianceSeed);
const ride: ChildRide = { childName: 'Amina N.', school: 'Kampala Preparatory School', route: 'Route A', status: 'picked_up', pickupTime: '07:18', maskedVehicleLocation: 'Near Makerere Hill • location masked for privacy', vehicleLabel: 'School Van • UAX 482B', pickupProof: 'Teacher gate confirmation + driver scan', confidence: 'confirmed' };
const rideHistory = [{ id: 'r1', route: 'Route A', status: 'picked_up', time: '07:18', confidence: 'confirmed' as OperationalConfidence }, { id: 'r2', route: 'Route A', status: 'dropped_off', time: '15:48', confidence: 'manually-verified' as OperationalConfidence }];
const schedule: ScheduleItem[] = [{ term: 'Term 1 2026', route: 'Route A', days: 'Mon–Fri', pickup: '07:15', dropoff: '15:45', feeUgx: 150000, status: 'paid' }, { term: 'Term 2 2026', route: 'Route A', days: 'Mon–Sat', pickup: '07:15', dropoff: '15:45', feeUgx: 150000, status: 'due' }];
const quickPayOptions = [{ label: 'MTN MoMo', hint: 'Pay in UGX' }, { label: 'Airtel Money', hint: 'Pay in UGX' }, { label: 'Card', hint: 'Visa / Mastercard' }] as const;
const notificationLogs: SmsUssdFallbackPayload[] = [{ messageId: 'sms_01', senderPhone: 'Kabiriti', gatewayProvider: 'africas_talking', rawText: 'CHILD PICKED UP OK', interpretedAction: 'CHECKIN', associatedChildId: 'child_001', processedAt: '2026-08-13T06:19:00Z', success: true, schoolId: 'school_ug_001', campusId: 'campus_1', confidence: 'confirmed' }];
const mobileMoneyDraft: TransportLedgerTransaction = { transactionId: 'TXN-UG-99001', organizationId: 'ORG-KAMPALA-01', parentId: 'PAR-88392', amountUgx: 150000, paymentMethod: 'mtn_momo', status: 'pending', termReference: 'Term 2 2026', createdAt: '2026-08-13T02:00:00Z', confidence: 'delayed', paymentMatchStatus: 'pending', paymentProvider: 'mtn_momo' };
const confidenceTone: Record<OperationalConfidence, string> = { confirmed: 'text-emerald-300', inferred: 'text-sky-300', delayed: 'text-amber-300', 'offline-received': 'text-violet-300', 'manually-verified': 'text-orange-300' };
const statusTone: Record<RideStatus, string> = { waiting: 'bg-amber-500/10 text-amber-200 ring-amber-500/20', picked_up: 'bg-sky-500/10 text-sky-200 ring-sky-500/20', en_route: 'bg-sky-500/10 text-sky-200 ring-sky-500/20', dropped_off: 'bg-emerald-500/10 text-emerald-200 ring-emerald-500/20' };

export default function ParentDashboardPage() {
  const rideSnapshots = listRideSnapshots();
  const liveRide = rideSnapshots[0]?.state;
  const [payments, setPayments] = useState<TransportLedgerTransaction[]>([mobileMoneyDraft]);
  const [selectedRail, setSelectedRail] = useState<'MTN MoMo' | 'Airtel Money' | 'Card'>('Card');
  const [booking, setBooking] = useState<VehicleBookingPreference>(bookingDefaults);
  const [accountMode, setAccountMode] = useState<'kids_mobility' | 'personal_ride'>('kids_mobility');
  const latestPayment = payments[0];
  const displayRide = liveRide ? { childName: 'Amina N.', school: liveRide.routeName, route: liveRide.routeName, status: liveRide.confidenceState === 'arrived' ? 'dropped_off' : 'en_route', pickupTime: '07:18', maskedVehicleLocation: liveRide.currentLocationLabel || 'Location masked', vehicleLabel: `${liveRide.vehicleKind === 'boda_boda' ? 'Boda Boda' : 'Car'} • live ride`, pickupProof: liveRide.confidenceNote || 'Live ride update', confidence: liveRide.confidence } : ride;
  useEffect(() => { void fetch(apiUrl('/api/safety/dispatcher/summary')).catch(() => undefined); }, []);
  const toggleWeekday = (day: BookingWeekday) => setBooking((prev) => { const current = prev.weeklyPattern ?? ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']; return { ...prev, weeklyPattern: current.includes(day) ? current.filter((d) => d !== day) : [...current, day] }; });
  const handleQuickPay = () => setPayments((prev) => [...prev, { ...mobileMoneyDraft, transactionId: `TXN-UG-${Date.now()}`, paymentMethod: selectedRail === 'Card' ? 'card' : selectedRail === 'MTN MoMo' ? 'mtn_momo' : 'airtel_money', paymentProvider: selectedRail === 'Card' ? 'card' : selectedRail === 'MTN MoMo' ? 'mtn_momo' : 'airtel_money', confidence: 'delayed', paymentMatchStatus: 'pending' }]);
  const navItems = [
    { label: 'Home', href: '#top', icon: Home },
    { label: 'My Rides', href: '#rides', icon: Route },
    { label: 'Track Ride', href: '/ride/tracker', icon: MapPinned },
    { label: 'Payments', href: '#payments', icon: CreditCard },
    { label: 'Notifications', href: '#notifications', icon: Bell },
    { label: 'Safety', href: '#safety', icon: ShieldAlert },
    { label: 'Profile', href: '#profile', icon: User },
  ] as const;
  const isKidsMode = accountMode === 'kids_mobility';

  return (<main id="top" className="min-h-screen bg-slate-950 text-slate-100"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_top,_rgba(56,189,248,0.16),_transparent_26%),radial-gradient(circle_at_80%_20%,_rgba(15,23,42,0.92),_transparent_30%)]" /><div className="pointer-events-none fixed inset-0 soft-grid opacity-[0.12]" />
    <section className="border-b border-white/5 bg-slate-950/80 backdrop-blur-2xl"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="space-y-4"><div className="inline-flex items-center gap-2 rounded-full border border-sky-400/20 bg-sky-500/10 px-3 py-1 text-xs font-semibold text-sky-100 shadow-sm shadow-sky-950/20"><ShieldCheck className="h-3.5 w-3.5" /> Parent / Rider account</div><div><h1 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">Parent Ride Companion</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300 sm:text-base">Low-bandwidth tracking, pickup alerts, payment shortcuts, and booking controls for school rides and community rides in Uganda.</p></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-3xl border border-white/8 bg-white/[0.04] p-4 shadow-sm shadow-black/10"><div className="text-xs uppercase tracking-[0.24em] text-slate-500">Account mode</div><div className="mt-1 text-base font-semibold text-white">{isKidsMode ? 'Kids Mobility' : 'Personal Ride'}</div></div><div className="rounded-3xl border border-white/8 bg-white/[0.04] p-4 shadow-sm shadow-black/10"><div className="text-xs uppercase tracking-[0.24em] text-slate-500">Current ride</div><div className={`mt-1 text-base font-semibold ${displayRide.confidence === 'confirmed' ? 'text-emerald-300' : 'text-sky-300'}`}>{displayRide.status.replace('_', ' ')}</div></div><div className="rounded-3xl border border-white/8 bg-white/[0.04] p-4 shadow-sm shadow-black/10"><div className="text-xs uppercase tracking-[0.24em] text-slate-500">Payment</div><div className="mt-1 text-base font-semibold text-white">{latestPayment.paymentProvider} • {latestPayment.status}</div></div></div></div><div className="flex flex-wrap gap-3"><button onClick={() => setAccountMode((m) => (m === 'kids_mobility' ? 'personal_ride' : 'kids_mobility'))} className="rounded-2xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-slate-200 backdrop-blur-xl hover:bg-white/10">Mode: {accountMode === 'kids_mobility' ? 'Kids Mobility Account' : 'Personal Ride Account'}</button><Link href="/ride/tracker" className="rounded-2xl bg-sky-500 px-4 py-2.5 text-sm font-semibold text-white shadow-[0_0_24px_rgba(56,189,248,0.18)] hover:bg-sky-400">Live tracker</Link><Link href="/dispatch" className="rounded-2xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-slate-200 backdrop-blur-xl hover:bg-white/10">Track dispatch</Link></div></div></div>
      <div className="border-t border-white/5 bg-slate-950/65"><div className="mx-auto max-w-7xl px-4 py-3 sm:px-6 lg:px-8"><div className="flex flex-wrap gap-2">{navItems.map((item) => item.href.startsWith('#') ? <a key={item.label} href={item.href} className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-3 py-2 text-xs font-medium text-slate-200 hover:bg-white/[0.08]"><item.icon className="h-3.5 w-3.5 text-sky-300" />{item.label}</a> : <Link key={item.label} href={item.href} className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-3 py-2 text-xs font-medium text-slate-200 hover:bg-white/[0.08]"><item.icon className="h-3.5 w-3.5 text-sky-300" />{item.label}</Link>)}</div></div></div></section>

    <section className="mx-auto grid max-w-7xl gap-4 px-4 py-5 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:px-8">
      <div className="space-y-4">
        <div className="glass-strong rounded-[2rem] p-5 shadow-2xl shadow-black/20 ring-1 ring-sky-400/10 sm:p-6">
          <div className="flex items-start justify-between gap-4"><div><div className="inline-flex items-center gap-2 rounded-full border border-sky-400/20 bg-sky-500/10 px-3 py-1 text-xs font-semibold text-sky-100">Active ride</div><h2 className="mt-3 text-2xl font-semibold tracking-tight text-white">{displayRide.childName} • {displayRide.school}</h2><p className="mt-1 text-sm text-slate-400">{displayRide.route}</p></div><div className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-medium ring-1 ${confidenceTone[displayRide.confidence]}`}>{displayRide.confidence}</div></div>
          <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="text-xs text-slate-500">Driver</div><div className="mt-1 text-sm font-semibold text-white">{displayRide.vehicleLabel}</div></div><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="text-xs text-slate-500">Pickup</div><div className="mt-1 text-sm font-semibold text-white">{displayRide.pickupTime}</div></div><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="text-xs text-slate-500">Location</div><div className="mt-1 text-sm font-semibold text-white">{displayRide.maskedVehicleLocation}</div></div><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="text-xs text-slate-500">Journey status</div><div className="mt-1 text-sm font-semibold text-white">{displayRide.status.replace('_', ' ')}</div></div></div>
          <div className="mt-4 rounded-2xl border border-sky-400/10 bg-sky-500/5 p-4"><div className="flex items-center justify-between gap-3 text-sm text-slate-200"><span className="font-medium text-white">Journey progress</span><span>Pickup • In transit • Handoff</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full bg-sky-400 ${displayRide.status === 'dropped_off' ? 'w-full' : displayRide.status === 'en_route' ? 'w-3/4' : 'w-1/2'}`} /></div><div className="mt-3 flex items-center justify-between text-xs text-slate-400"><span>Pickup</span><span>Live tracking</span><span>Drop-off</span></div></div>
          <div className="mt-5 grid gap-3 md:grid-cols-3"><button disabled className="rounded-2xl border border-sky-400/20 bg-sky-500/10 px-4 py-4 text-left text-sm text-sky-100 opacity-80"><div className="flex items-center gap-2 font-semibold"><PhoneCall className="h-4 w-4" /> Call Driver</div><div className="mt-1 text-xs text-sky-100/75">Preview only until communication is connected</div></button><button disabled className="rounded-2xl border border-sky-400/20 bg-sky-500/10 px-4 py-4 text-left text-sm text-sky-100 opacity-80"><div className="flex items-center gap-2 font-semibold"><MessageSquareText className="h-4 w-4" /> Message Driver</div><div className="mt-1 text-xs text-sky-100/75">Preview only until messaging is connected</div></button><button className="rounded-2xl border border-red-500/20 bg-red-500/10 px-4 py-4 text-left text-sm text-red-100"><div className="flex items-center gap-2 font-semibold"><ShieldAlert className="h-4 w-4" /> Safety / SOS</div><div className="mt-1 text-xs text-red-100/80">Keep separate from ordinary communication</div></button></div>
          <div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-slate-200">Where are you?</span><span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-slate-200">I’m at the pickup</span><span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-slate-200">Please call me</span><span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-slate-200">I can’t find you</span></div>
        </div>

        {isKidsMode ? <div id="safety" className="glass rounded-[1.75rem] p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-white">School safety card</h2><p className="mt-1 text-sm text-slate-400">Pickup verification and handoff status for kids mobility.</p></div><ShieldCheck className="h-5 w-5 text-emerald-300" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="text-xs text-slate-500">Child status</div><div className="mt-1 text-sm font-semibold text-white">{displayRide.status.replace('_', ' ')}</div></div><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="text-xs text-slate-500">Pickup verification</div><div className="mt-1 text-sm font-semibold text-white">{displayRide.pickupProof}</div></div><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="text-xs text-slate-500">Handoff status</div><div className="mt-1 text-sm font-semibold text-white">Protected</div></div><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="text-xs text-slate-500">Parent confirmation</div><div className="mt-1 text-sm font-semibold text-white">Waiting on parent review</div></div></div></div> : null}

        <div id="rides" className="glass-strong rounded-[2rem] p-5 shadow-2xl shadow-black/20 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-white">Booking controls</h2><p className="mt-1 text-sm text-slate-400">Pick vehicle, payment, cadence, and weekly days for school rides or community rides.</p></div><BusFront className="h-5 w-5 text-sky-300" /></div><div className="mt-5 grid gap-3 md:grid-cols-3">{(['car', 'boda_boda'] as const).map((vehicleClass) => <button key={vehicleClass} onClick={() => setBooking((prev) => ({ ...prev, vehicleClass }))} className={`rounded-2xl border px-4 py-3 text-left text-sm ${booking.vehicleClass === vehicleClass ? 'border-sky-500/40 bg-sky-500/10 text-sky-100' : 'border-white/8 bg-white/[0.04] text-slate-200'}`}>{vehicleClass === 'car' ? 'Car' : 'Boda Boda'}</button>)}</div><div className="mt-4 flex flex-wrap gap-2">{(['daily', 'weekly', 'termly'] as BookingRideCadence[]).map((cadence) => <button key={cadence} onClick={() => setBooking((prev) => ({ ...prev, cadence }))} className={`rounded-full px-3 py-1 text-xs ${booking.cadence === cadence ? 'bg-sky-500/10 text-sky-200' : 'bg-white/5 text-slate-300'}`}>{cadence}</button>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-3">{quickPayOptions.map((opt) => <button key={opt.label} onClick={() => setSelectedRail(opt.label)} className={`rounded-2xl px-4 py-3 text-left text-sm ${selectedRail === opt.label ? 'bg-white/10 text-white' : 'bg-white/5 text-slate-300'}`}><div className="font-medium">{opt.label}</div><div className="text-xs opacity-80">{opt.hint}</div></button>)}</div>{booking.cadence === 'weekly' && <div className="mt-4 flex flex-wrap gap-2">{weekdays.map((day) => <button key={day} onClick={() => toggleWeekday(day)} className={`rounded-full px-3 py-1 text-xs ${booking.weeklyPattern?.includes(day) ? 'bg-emerald-500/10 text-emerald-200' : 'bg-white/5 text-slate-300'}`}>{day.slice(0, 3).toUpperCase()}</button>)}</div>}<div className="mt-4 rounded-2xl border border-white/8 bg-white/[0.04] p-4 text-sm text-slate-300">Weekly defaults to Mon–Fri; add Saturday when needed.</div><div className="mt-4 rounded-2xl border border-white/8 bg-slate-950/60 p-4 text-sm text-slate-300"><div className="text-xs uppercase tracking-[0.25em] text-slate-500">Compliance status</div><div className={`mt-2 font-semibold ${bookingComplianceSeed.blocked ? 'text-red-300' : bookingComplianceSeed.state === 'attention_required' ? 'text-amber-300' : 'text-emerald-300'}`}>{bookingComplianceSeed.state.replace('_', ' ')}</div><div className="mt-1 text-xs text-slate-400">{bookingComplianceSummary.reason} • {bookingComplianceSummary.attentionCount} attention items</div></div><button onClick={handleQuickPay} className="mt-4 rounded-2xl bg-sky-500 px-4 py-3 text-sm font-semibold text-white hover:bg-sky-400">Save booking + start payment</button></div>

        <div id="history" className="glass rounded-[1.75rem] p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-white">Ride history</h2><p className="mt-1 text-sm text-slate-400">Pickup and drop-off proof with confidence labels.</p></div><Clock3 className="h-5 w-5 text-sky-300" /></div><div className="mt-5 space-y-3">{rideHistory.map((item) => <div key={item.id} className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="flex items-center justify-between gap-3"><div><div className="font-medium text-white">{item.route}</div><div className="text-xs text-slate-400">{item.time}</div></div><div className={`rounded-full px-2.5 py-1 text-[11px] ${confidenceTone[item.confidence]}`}>{item.confidence}</div></div></div>)}</div></div>
      </div>

      <div className="space-y-4">
        <div className="glass-strong rounded-[2rem] p-5 shadow-2xl shadow-black/20 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-white">Upcoming rides</h2><p className="mt-1 text-sm text-slate-400">School ride and community ride schedule preview.</p></div><CalendarRange className="h-5 w-5 text-sky-300" /></div><div className="mt-5 space-y-3">{schedule.map((item) => <div key={`${item.term}-${item.route}`} className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-semibold text-white">{item.term}</div><div className="mt-1 text-xs text-slate-400">{item.route} • {item.days}</div></div><div className={`rounded-full px-2.5 py-1 text-[11px] ${item.status === 'paid' ? 'bg-emerald-500/10 text-emerald-200' : item.status === 'due' ? 'bg-amber-500/10 text-amber-200' : 'bg-sky-500/10 text-sky-200'}`}>{item.status}</div></div><div className="mt-3 flex items-center justify-between text-sm text-slate-300"><span>Pickup {item.pickup}</span><span>Drop-off {item.dropoff}</span></div><div className="mt-3 text-xs text-slate-400">{item.feeUgx.toLocaleString()} UGX</div></div>)}</div></div>

        <div id="payments" className="glass rounded-[1.75rem] p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-white">Payments</h2><p className="mt-1 text-sm text-slate-400">Card stays available alongside mobile money.</p></div><CreditCard className="h-5 w-5 text-sky-300" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="text-xs text-slate-500">Selected</div><div className="mt-1 text-sm font-semibold text-white">{selectedRail}</div></div><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-4"><div className="text-xs text-slate-500">Latest payment</div><div className="mt-1 text-sm font-semibold text-white">{latestPayment.paymentProvider} • {latestPayment.status}</div></div></div><button onClick={handleQuickPay} className="mt-4 rounded-2xl bg-sky-500 px-4 py-3 text-sm font-semibold text-white hover:bg-sky-400">Save booking + start payment</button></div>

        <div id="notifications" className="glass rounded-[1.75rem] p-5 sm:p-6"><div className="flex items-center gap-3"><Bell className="h-5 w-5 text-sky-300" /><div><h3 className="text-lg font-semibold text-white">Notifications</h3><p className="text-sm text-slate-400">Parents receive ride alerts and updates.</p></div></div><div className="mt-4 space-y-2 text-sm text-slate-300"><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-3">{notificationLogs[0].rawText}</div><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-3">Arrival alert, route deviation, and SOS are all supported.</div></div></div>

        <div id="profile" className="glass rounded-[1.75rem] p-5 sm:p-6"><div className="flex items-center gap-3"><User className="h-5 w-5 text-sky-300" /><div><h3 className="text-lg font-semibold text-white">Profile</h3><p className="text-sm text-slate-400">Account preferences and route identity.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-3"><div className="text-xs text-slate-500">Mode</div><div className="mt-1 text-sm font-semibold text-white">{accountMode === 'kids_mobility' ? 'Kids Mobility Account' : 'Personal Ride Account'}</div></div><div className="rounded-2xl border border-white/8 bg-white/[0.04] p-3"><div className="text-xs text-slate-500">Safety status</div><div className="mt-1 text-sm font-semibold text-white">Verified ride support</div></div></div></div>
      </div>
    </section>
  </main>);
}
