// PoleSafe — Family Sharing Model
// Linked accounts for parents sharing kid monitoring

const mongoose = require('mongoose');

// ============================================================
// FAMILY LINK — Connects two parent accounts
// ============================================================
const familyLinkSchema = new mongoose.Schema({
  // The parent who created the link (primary)
  primaryParentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  // The co-parent who joined via code
  coParentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null,
  },
  // Join code (6 characters, generated by primary)
  joinCode: {
    type: String,
    required: true,
    unique: true,
    length: 6,
  },
  // Status
  status: {
    type: String,
    enum: ['pending', 'active', 'removed'],
    default: 'pending',
  },
  // What's shared
  shareKids: { type: Boolean, default: true },       // Both see kids
  shareTracking: { type: Boolean, default: true },   // Both can track rides
  coParentCanBook: { type: Boolean, default: true },  // Co-parent can book rides
  coParentCanCancel: { type: Boolean, default: true }, // Co-parent can cancel own bookings
  
  // Metadata
  createdAt: { type: Date, default: Date.now },
  activatedAt: { type: Date },
  removedAt: { type: Date },
});

// ============================================================
// RIDE BOOKING CONFLICT — Prevents double-booking
// ============================================================
const rideReservationSchema = new mongoose.Schema({
  childId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Child',
    required: true,
  },
  date: { type: String, required: true },  // YYYY-MM-DD
  timeSlot: { type: String, required: true },  // e.g. "7:00 AM"
  period: { type: String, enum: ['morning', 'afternoon'], required: true },
  rideId: { type: mongoose.Schema.Types.ObjectId, ref: 'Ride', required: true },
  bookedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
});

rideReservationSchema.index({ childId: 1, date: 1, timeSlot: 1 }, { unique: true });

module.exports = {
  FamilyLink: mongoose.model('FamilyLink', familyLinkSchema),
  RideReservation: mongoose.model('RideReservation', rideReservationSchema),
};
