import type { z } from 'zod';
import { createSosInputSchema, complianceAttentionEventSchema, complianceSlaMetricSchema, dispatcherDashboardResponseSchema, geoPointSchema, incidentActionInputSchema, incidentAuditEntrySchema, incidentContactRelaySchema, incidentDeviceStatusSchema, incidentSeveritySchema, incidentStatusSchema, incidentTriggerTypeSchema, localVerificationRecordSchema, maskIncidentInputSchema, resolveIncidentInputSchema, safetyIncidentSchema, ugandaBookingInputSchema, unmaskIncidentInputSchema } from './schemas';

export type IncidentTriggerType = z.infer<typeof incidentTriggerTypeSchema>;
export type IncidentSeverity = z.infer<typeof incidentSeveritySchema>;
export type IncidentStatus = z.infer<typeof incidentStatusSchema>;
export type GeoPoint = z.infer<typeof geoPointSchema>;
export type IncidentDeviceStatus = z.infer<typeof incidentDeviceStatusSchema>;
export type IncidentAuditEntry = z.infer<typeof incidentAuditEntrySchema>;
export type IncidentContactRelay = z.infer<typeof incidentContactRelaySchema>;
export type SafetyIncident = z.infer<typeof safetyIncidentSchema>;
export type CreateSosInput = z.infer<typeof createSosInputSchema>;
export type IncidentActionInput = z.infer<typeof incidentActionInputSchema>;
export type ResolveIncidentInput = z.infer<typeof resolveIncidentInputSchema>;
export type MaskIncidentInput = z.infer<typeof maskIncidentInputSchema>;
export type DispatcherDashboardResponse = z.infer<typeof dispatcherDashboardResponseSchema>;
export type ComplianceAttentionEvent = z.infer<typeof complianceAttentionEventSchema>;
export type ComplianceSlaMetric = z.infer<typeof complianceSlaMetricSchema>;
export type LocalVerificationRecord = z.infer<typeof localVerificationRecordSchema>;
export type UgandaBookingInput = z.infer<typeof ugandaBookingInputSchema>;
export type UnmaskIncidentInput = z.infer<typeof unmaskIncidentInputSchema>;
